[project]
name = "live-line-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anzu324"}
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.4",
    "pyqtdarktheme>=2.1.0",
    "pyside6>=6.11.2",
]

[project.scripts]
live-line-builder = "live_line_builder:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-qt>=4.5.0",
    "ruff>=0.16.5",
]

# Tool settings
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]


[tool.mypy]
python_version = "3.14" # 使用しているPythonバージョン
warn_return_any = true
warn_unused_configs = true

# Pydantic 用プラグインの有効化
plugins = [
    "pydantic.mypy"
]

# Pydantic プラグインの細かな挙動設定（任意）
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[[tool.mypy.overrides]]
module = "qdarktheme.*"
ignore_missing_imports = true


[tool.pytest.ini_options]
pythonpath = ["src","tests"]
